#kubectl get daemonsets -o wide
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app-container
          image: nginx:latest
          ports:
            - containerPort: 80
